global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]  # <- Render internal network name
    metrics_path: "/metrics"
    scrape_interval: 2s
